
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    username character varying(255) NOT NULL,
    owner_id bigint NOT NULL,
    is_active boolean,
    role_id bigint,
    is_deleted boolean DEFAULT false NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);


ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.pending_action (
    id bigint NOT NULL,
    action_type character varying(255),
    created_at timestamp(6) without time zone,
    entity_id bigint,
    last_attempt_at timestamp(6) without time zone,
    service character varying(255),
    status character varying(255)
);


ALTER TABLE public.pending_action ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pending_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roles_id_seq OWNER TO huy;


ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    account_id bigint NOT NULL
);

ALTER TABLE public.social_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.verification_code (
    id bigint NOT NULL,
    code character varying(255),
    email character varying(255),
    expiry_time timestamp(6) without time zone,
    is_verified boolean
);


ALTER TABLE public.verification_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


COPY public.accounts (id, created_at, password, updated_at, username, owner_id, is_active, role_id, is_deleted, is_verified) FROM stdin;
3	2025-09-23 23:44:11.127502+07	$2a$10$lhRXnNei6O8aPqOszrpp0eACU.CnkrgalahwatWFtNnIlNWCNwk4O	2025-10-28 22:29:54.155702+07	admin	3	t	1	f	t
55	2025-10-28 20:38:47.781827+07	$2a$10$mokou1dd9nj4VRS94Z8Z5evskl0oSiXb47uUJ9KXCHB6FevJx.YTK	2025-10-28 20:38:47.781827+07	n21dccn037@student.ptithcm.edu.vn	22	t	4	f	t
50	2025-10-26 14:52:21.9881+07	$2a$10$smywRLqrPPNuAd0HrcEDEONKtawsTQrpuOjdqLdekBX0Mti254SFu	2025-11-02 12:34:42.554859+07	huy1	17	t	4	f	t
57	2025-10-28 22:29:55.880364+07	$2a$10$J5yVxdzMKcpX28lIyCkXEuk9YOUcXPLHODpNvEB409z69SFmZHkQa	2025-11-02 14:09:49.597933+07	test2	36	t	2	f	t
25	2025-09-26 16:44:41.773541+07	$2a$10$09sN1/TmLtiHdiWwtYoxBOy2KKpreMFjhN6Rjp9L0yulmy.dy6qoq	2025-10-23 21:11:17.86851+07	customer1	3	t	4	f	t
24	2025-09-26 16:33:27.106667+07	$2a$10$t4LEXejVae53ANyXTdK4r.FETvbg2yQG9heNt7rf1dTjy35lFfzi2	2025-11-03 22:00:38.638433+07	user1	22	t	3	f	f
58	2025-11-04 15:45:10.107803+07	$2a$10$BiCl41bgEo.S4WgzeOJhEOHAGaHiW7rUQ181SwXwrUbkxC9zZdYdy	2025-11-04 15:45:10.107803+07	huy3	24	t	4	f	f
\.



COPY public.pending_action (id, action_type, created_at, entity_id, last_attempt_at, service, status) FROM stdin;
\.



COPY public.roles (id, name, description, created_at, updated_at) FROM stdin;
1	ADMIN	\N	2025-09-28 23:26:24.247454+07	2025-09-28 23:26:24.247454+07
2	MANAGER	\N	2025-09-28 23:26:24.247454+07	2025-09-28 23:26:24.247454+07
3	STAFF	\N	2025-09-28 23:26:24.247454+07	2025-09-28 23:26:24.247454+07
4	CUSTOMER	\N	2025-09-28 23:26:24.247454+07	2025-09-28 23:26:24.247454+07
\.


COPY public.social_accounts (id, provider, provider_id, account_id) FROM stdin;
6	google	108549917066849111639	50
7	google	115497819864610158277	55
\.



COPY public.verification_code (id, code, email, expiry_time, is_verified) FROM stdin;
\.


SELECT pg_catalog.setval('public.account_id_seq', 58, true);



SELECT pg_catalog.setval('public.pending_action_id_seq', 16, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.social_accounts_id_seq', 7, true);


--
-- Name: verification_code_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.verification_code_id_seq', 42, true);


--
-- Name: accounts account_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: pending_action pending_action_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.pending_action
    ADD CONSTRAINT pending_action_pkey PRIMARY KEY (id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts ukgex1lmaqpg0ir5g1f5eftyaa1; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukgex1lmaqpg0ir5g1f5eftyaa1 UNIQUE (username);


--
-- Name: social_accounts ukor4mt9h1be15geitov4le5ofd; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT ukor4mt9h1be15geitov4le5ofd UNIQUE (provider, provider_id);


--
-- Name: verification_code verification_code_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.verification_code
    ADD CONSTRAINT verification_code_pkey PRIMARY KEY (id);


--
-- Name: accounts fk_role; Type: FK CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE SET NULL;


--
-- Name: social_accounts fkfyytrb9k3ko5dns3e5xusv198; Type: FK CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT fkfyytrb9k3ko5dns3e5xusv198 FOREIGN KEY (account_id) REFERENCES public.accounts(id);

