SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.promotion_usages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    customer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    promotion_id bigint NOT NULL
);


ALTER TABLE public.promotion_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotion_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    applicable_brands jsonb,
    applicable_categories jsonb,
    applicable_products jsonb,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_staff_id bigint,
    description text,
    discount_type character varying(20),
    discount_value numeric(15,2),
    end_date timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    max_discount_amount numeric(15,2),
    min_order_amount numeric(15,2),
    name character varying(200) NOT NULL,
    promotion_type character varying(20) NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    usage_count integer NOT NULL,
    usage_limit integer,
    usage_limit_per_customer integer,
    CONSTRAINT promotions_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED_AMOUNT'::character varying])::text[]))),
    CONSTRAINT promotions_promotion_type_check CHECK (((promotion_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED_AMOUNT'::character varying, 'FREE_SHIPPING'::character varying])::text[])))
);


ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.promotion_usages
    ADD CONSTRAINT promotion_usages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);


COPY public.promotion_usages (id, created_at, customer_id, order_id, promotion_id) FROM stdin;
1	2025-11-03 20:23:01.854953	17	100	4
2	2025-11-03 21:01:28.837737	22	101	4
3	2025-11-03 21:46:44.995069	3	102	5
4	2025-11-04 16:00:10.852582	17	106	3
\.


COPY public.promotions (id, applicable_brands, applicable_categories, applicable_products, code, created_at, created_by_staff_id, description, discount_type, discount_value, end_date, is_active, max_discount_amount, min_order_amount, name, promotion_type, start_date, updated_at, usage_count, usage_limit, usage_limit_per_customer) FROM stdin;
4	\N	\N	[10]	PROMO2	2025-11-03 17:57:25.898765	3	Giam gia len den 20%	\N	20.00	2025-11-12 23:22:00	t	100000.00	500000.00	Giam gia dac biet	PERCENTAGE	2025-10-29 20:00:00	2025-11-03 21:45:17.923047	2	3	1
5	\N	\N	[10]	PROMO3	2025-11-03 21:24:55.242475	3	Khuyen mai cho IP16	\N	50000.00	2025-11-04 17:00:00	f	50000.00	10000.00	Giam gia soc	FIXED_AMOUNT	2025-11-03 18:11:00	2025-11-03 21:46:44.998088	1	1	1
6	\N	\N	\N	PROMO4	2025-11-03 21:44:31.093526	3	Khuyen mai xieu xiu	\N	10.00	2025-11-06 17:10:00	t	100000.00	100000.00	Giam gia mua he	PERCENTAGE	2025-11-05 17:10:00	2025-11-04 15:59:05.087088	0	1	1
3	\N	\N	[10]	TEST1	2025-11-03 15:46:24.950273	3	ada  das	\N	10.00	2025-11-04 23:00:00	t	10000.00	100000.00	Giam gtia	PERCENTAGE	2025-10-31 23:00:00	2025-11-04 16:00:10.86558	1	10	1
\.

