
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.addresses (
    id bigint NOT NULL,
    city character varying(100) NOT NULL,
    created_at timestamp with time zone,
    district character varying(100),
    is_main boolean,
    phone character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    updated_at timestamp with time zone,
    ward character varying(100),
    customer_id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.customer_segments (
    id bigint NOT NULL,
    benefits jsonb,
    conditions jsonb,
    created_at timestamp with time zone,
    description text,
    name character varying(50) NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.customer_segments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_segments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.customers (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    date_of_birth date,
    email character varying(100),
    full_name character varying(100),
    gender character varying(10),
    is_active boolean,
    last_order_date timestamp with time zone,
    phone character varying(20),
    preferences jsonb,
    tags jsonb,
    total_orders integer,
    total_spent numeric(15,2),
    updated_at timestamp with time zone,
    segment_id bigint
);


ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


COPY public.addresses (id, city, created_at, district, is_main, phone, street, updated_at, ward, customer_id, name) FROM stdin;
4	Tinh	2025-10-20 11:22:41.993613+07	Quan	f	141233311	so nhA	2025-10-20 11:22:41.993613+07	Phuong	3	Huy2
6	Tinh ASRT	2025-10-24 11:03:42.536113+07	Quan C	t	0123141244	34 so nha 	2025-10-24 11:03:42.536113+07	Phuong abc	3	Huy 3
3	Quy nhon1	2025-10-19 17:57:39.659726+07	dasdas	f	0998831232	23 Mai duong2	2025-10-19 17:57:39.659726+07	Quang trung	3	Huy1
8	Thß╗º ─Éß╗®c	2025-10-27 22:05:56.894367+07	T─âng Nhãín Ph├║ A	t	0844123312	43 Phß║ím Ng┼® L├úo	2025-10-27 22:05:56.894367+07	Bß║┐n Ngh├®	17	Huy ─Éß║Àng
9	Ho Chi Minh	2025-11-03 21:01:16.749509+07	Quant c	t	0055512244	acb zcd	2025-11-03 21:01:16.749509+07	Phuong A 	22	Dia chi 1
10	dasdsa	2025-11-04 15:57:56.480991+07	asdas	t	1231412	asdasd	2025-11-04 15:57:56.480991+07	123 sa da	24	Dia chi1
\.


--
-- Data for Name: customer_segments; Type: TABLE DATA; Schema: public; Owner: huy
--

COPY public.customer_segments (id, benefits, conditions, created_at, description, name, updated_at) FROM stdin;
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: huy
--

COPY public.customers (id, created_at, date_of_birth, email, full_name, gender, is_active, last_order_date, phone, preferences, tags, total_orders, total_spent, updated_at, segment_id) FROM stdin;
17	2025-10-26 14:52:21.888093+07	\N	dangquochuy26122003@gmail.com	Dang Quo chuyh	Nam	t	\N	0994124421	\N	\N	0	0.00	2025-10-26 14:52:21.888093+07	\N
24	2025-11-04 15:45:09.996909+07	\N	\N		\N	t	\N		\N	\N	0	0.00	2025-11-04 15:45:09.996909+07	\N
3	2025-09-26 16:44:41.624386+07	2025-10-22	customer1@gmail.com	test 12	Nam	t	\N	adsfads 2	\N	\N	0	0.00	2025-09-26 16:44:41.624386+07	\N
22	2025-10-28 20:38:47.692874+07	\N	n21dccn037@student.ptithcm.edu.vn	huy2	\N	t	\N		\N	\N	0	0.00	2025-10-28 20:38:47.692874+07	\N
\.


--
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.addresses_id_seq', 10, true);


--
-- Name: customer_segments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.customer_segments_id_seq', 1, false);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: huy
--

SELECT pg_catalog.setval('public.customers_id_seq', 24, true);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: customer_segments customer_segments_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.customer_segments
    ADD CONSTRAINT customer_segments_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: customer_segments uk9v933bm211015c3i1vh4qg1iq; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.customer_segments
    ADD CONSTRAINT uk9v933bm211015c3i1vh4qg1iq UNIQUE (name);


--
-- Name: customers ukrfbvkrffamfql7cjmen8v976v; Type: CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukrfbvkrffamfql7cjmen8v976v UNIQUE (email);


--
-- Name: customers fk72867512ip0jxs6ni8vm0e5rn; Type: FK CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fk72867512ip0jxs6ni8vm0e5rn FOREIGN KEY (segment_id) REFERENCES public.customer_segments(id);


--
-- Name: addresses fkhrpf5e8dwasvdc5cticysrt2k; Type: FK CONSTRAINT; Schema: public; Owner: huy
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fkhrpf5e8dwasvdc5cticysrt2k FOREIGN KEY (customer_id) REFERENCES public.customers(id);


